#! /bin/sh

sxhkd &
nm-applet &
[ ! -s ~/.config/mpd/pid ] && mpd &

# Polybar start script (Will restart with restart of bspwm)
$HOME/.config/polybar/launch.sh

# Monitor setup

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-1 -d 10 11 12

bspc config border_width        0
bspc config window_gap          0
bspc config top_padding         24 # set to match polybar

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^7' state=floating follow=on
bspc rule -a Firefox desktop='^2' state=tiled
bspc rule -a mpv state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off
bspc rule -a Emacs desktop='^3' state=tiled

# display compositor
#if [ -x /usr/bin/picom ]; then
#    picom -b --experimental-backends &
#fi

ps -A | grep picom ; killall -q picom || picom -b --experimental-backends --backend glx --config /home/sebastian/.config/picom/picom.conf &
# manage wallpaper
wal -R

#if [ -x /usr/bin/feh ]; then
#    feh --bg-fill "$(< "${HOME}/.cache/wal/wal")"
#fi
